Changed Javadoc comments to XML comments.
opentok/Opentok-.NET-SDK pull request #150
Opened 2020-10-02 21:36 UTC by dlemstra

This PR changes the Javadoc comments to XML comments to make sure that comments are visibile in intellisense.

2020-10-03 14:56 UTC, slorello89 commented
Hi @dlemstra - thanks for this PR (been on my todo list for a while) I'll need to check to see if it's something we can support as the javadocs are actually what we use to build a lot of our documentation on the developer website.

@jeffswartz - Would this break everything?

2020-10-16 16:05 UTC, jeffswartz approved these changes

2020-10-16 16:07 UTC, jeffswartz commented
> Hi @dlemstra - thanks for this PR (been on my todo list for a while) I'll need to check to see if it's something we can support as the javadocs are actually what we use to build a lot of our documentation on the developer website.
> 
> @jeffswartz - Would this break everything?

Should be good. We have some processing scripts for the Windows SDK reference that work with .NET style code comments. I may need to fiddle with that to parse the generated content and get it into the developer center.

2020-10-16 18:25 UTC, jeffswartz requested changes

2020-10-16 18:25 UTC, jeffswartz commented on OpenTok/OpenTok.cs
> +    /// and the API secret for your <see href="https://tokbox.com/account">OpenTok project</see>.
These external links do not work (at least with Doxygen generating the docs). Can you please change all `see` links to external URLs to use `a` tags (throughout)?

```suggestion
    /// and the API secret for your <a href="https://tokbox.com/account">OpenTok project</a>.
```

2020-10-17 07:16 UTC, dlemstra commented on OpenTok/OpenTok.cs
> +    /// and the API secret for your <see href="https://tokbox.com/account">OpenTok project</see>.
Did you confirm that `a` works? `<see href="">` appears to be the official syntax (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/see#remarks) but it looks like this is not supported by Doxygen (http://doxygen.nl/manual/xmlcmds.html).

2020-10-20 13:34 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +    /// and the API secret for your <see href="https://tokbox.com/account">OpenTok project</see>.
It looks like Visual Studio supports both - @jeffswartz - does doxygen support this as well?

2020-10-27 21:28 UTC, jeffswartz commented on OpenTok/OpenTok.cs
> +    /// and the API secret for your <see href="https://tokbox.com/account">OpenTok project</see>.
Yes, the `a` tag works in Doxygen. And it does not support the `<see href >` syntax.

2020-10-28 08:04 UTC, dlemstra commented on OpenTok/OpenTok.cs
> +    /// and the API secret for your <see href="https://tokbox.com/account">OpenTok project</see>.
Thanks @jeffswartz. Will update the links later today.

2020-10-28 17:21 UTC, dlemstra commented
@slorello89 I always rebase my PR's. You might want to ask if someone is okay with you merging into their branch next time. No biggie but something to consider in the future.

The links have been changed back to `<a/>`. Please let me know if I need to make additional changes.

2020-10-28 18:32 UTC, slorello89 approved these changes
Hi @dlemstra - sorry I pressed the GitHub `update branch` button in the PR to make sure that everything was building correctly (the windows-latest image change and removed some of the .NET Core versions the tests were running against so I needed to update the action).

Pulled everything into Visual Studio and it looks good to me. @jeffswartz - if you could just run this through Doxygen to make sure everything looks good I think we're good to merge.

2020-11-04 06:16 UTC, jeffswartz approved these changes

2020-11-04 13:57 UTC, slorello89 commented
Hi @dlemstra - thanks so much for this - it's a great improvement!

2020-11-04 13:57 UTC, merged