Implements SetArchiveLayout and async/await
opentok/Opentok-.NET-SDK pull request #156
Opened 2021-01-19 14:36 UTC by gleborgne

SetArchiveLayout method was not implemented and required for our business. We also implements async/await to avoid IO blocking threads and improve performances.

2021-01-26 18:34 UTC, slorello89 requested changes
Hello @gleborgne - definitely a quality PR and a solid contribution - see my comments contained in here - but I do have a bit of a concern about using the Wait/Result portions of the async methods as in certain environments they can introduce deadlocks in single-threaded environments as it can block the current thread, which may be needed to finish executing the async portions of the method underneath it. 

Realistically we should be maintaining a sync/async version of all these methods and those methods should be sync or async all the way up and down the stack.

Also - there's a `OpenTokSDK.csproj` that was created somehow - not quite sure where that came from - but everything should be in OpenTok.csproi.

Thanks!

2021-01-26 18:34 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +        {
For these synchronous methods, we should maintain their current pattern, I'm concerned that we're exposing ea deadlock condition here if you end up running this on a single-threaded webserver. I'm ok with keeping a method for each sync/async but they should be sync/async all the way up and down the stack.

2021-01-26 18:34 UTC, slorello89 commented on OpenTok/Util/HttpClient.cs
>                                          Dictionary<string, object> bodyData)
Same with the DoRequest method - would like to keep this sync down the stack.

2021-01-26 18:34 UTC, slorello89 commented on OpenTokTest/OpenTokTest.cs
> -            mockClient.Setup(httpClient => httpClient.Post(It.IsAny<string>(), It.IsAny<Dictionary<string, string>>(), It.IsAny<Dictionary<string, object>>())).Returns(returnString);
will probably need to do 2 versions of these tests to test each sync/async method.

2021-01-27 11:41 UTC, gleborgne commented
I refactor to have distinc async and non async path in the code.

2021-02-03 20:47 UTC, slorello89 commented
@gleborgne - FYI I'm updating your branch (updating the GH actions) - so make sure you do a pull before proceeding

2021-02-03 20:48 UTC, slorello89 requested changes

2021-02-03 20:51 UTC, slorello89 requested changes

2021-02-03 20:51 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +                task.Wait();
Still using Task.Wait()

2021-02-03 20:51 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +                task.Wait();
Still using Task.Wait()

2021-02-03 20:51 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +                task.Wait();
Still using Task.Wait()

2021-02-03 20:51 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +                task.Wait();
Still using Task.Wait()

2021-02-03 20:51 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +                task.Wait();
Still using Task.Wait()

2021-02-03 20:51 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +                task.Wait();
Still using Task.Wait()

2021-02-03 20:51 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +                task.Wait();
Still using Task.Wait()

2021-02-03 20:51 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +                task.Wait();
Still using Task.Wait()

2021-02-03 20:51 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +                task.Wait();
Still using Task.Wait()

2021-02-03 20:51 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +                task.Wait();
Still using Task.Wait()

2021-02-03 20:51 UTC, slorello89 commented on OpenTok/OpenTok.cs
> +                task.Wait();
Still using Task.Wait()

2021-11-12 10:27 UTC, matt-lethargic commented
Hi @gleborgne thank you for the PR, unfortunately, this is now out of date and seems like the comments were not addressed. SetArchiveLayout has been implemented all be it non-async. Are you happy to close this PR and I'll create a ticket for me to move over the remaining non-async methods sometime this week or next?

2022-02-10 00:53 UTC, jeffswartz requested changes

2022-02-10 00:53 UTC, jeffswartz commented on OpenTok/OpenTok.cs
> +        /// Sets the layout type for the broadcast. For a description of layout types, see
```suggestion
        /// Sets the layout type for the archive. For a description of layout types, see
```

2022-02-10 00:53 UTC, jeffswartz commented on OpenTok/OpenTok.cs
> +        /// <param name="archiveId">The broadcast ID of the broadcasting session.</param>
```suggestion
        /// <param name="archiveId">The archive ID.</param>
```

2022-02-10 00:53 UTC, jeffswartz commented on OpenTok/OpenTok.cs
> +        /// <param name="layout">The BroadcastLayout that defines layout options for the broadcast.</param>
```suggestion
        /// <param name="layout">The ArchiveLayout that defines layout options for the archive.</param>
```

(And make similar edits for the Async version of the method.

2022-04-13 07:53 UTC, closed without merging