Implementing Dial method for initiating a SIP call
opentok/Opentok-.NET-SDK pull request #166
Opened 2021-11-10 13:37 UTC by matt-lethargic

- DEVX-5647
 - DEVX-5665

2021-11-11 12:24 UTC, SecondeJK commented on OpenTok/OpenTok.cs
> +        {
One extra feature in the PHP SDK at this point is that it checks that the sessionID belongs to the Client's API key.

2021-11-12 09:33 UTC, matt-lethargic commented on OpenTok/OpenTok.cs
> +        {
Having a look at this now, think we have the code for this already.

2021-11-12 10:05 UTC, matt-lethargic commented on OpenTok/OpenTok.cs
> +        {
Added session Id validation to methods

2021-11-15 17:16 UTC, jeffswartz requested changes

2021-11-15 17:16 UTC, jeffswartz commented on OpenTok/OpenTok.cs
> +        public Task DialAsync(string sessionId, string token, string sipUri, DialOptions options = null)
Why are we adding this `DialAsync()` method in addition the the `Dial()` method? Other methods of the SDK do not have corresponding "Async" methods. Can we remove this method?

2021-11-15 17:16 UTC, jeffswartz commented on OpenTok/OpenTok.cs
> +        {
Re. `DialOptions`: In other methods of the, options are enumerated as individual parameters of the method. For example, the `OpenTok.StartArchive()` method includes hasVideo, hasAudio, outputMode, resolution, and layout options, instead of an `ArchiveOptions` parameter (and class). For consistency, can we move these options to  individual parameters of the `OpenTok.Dial()` method? (And if we do, the userName and password options can be added as parameters of the `OpenTok.Dial()` method as well.)

2021-11-15 17:16 UTC, jeffswartz commented on OpenTok/DialAuth.cs
> +    public class DialAuth
Can we add these as properties of the `DialOptions` class ... or (per my suggestion below) as parameters of the `OpenTok.Dial()` method?

2021-11-22 22:52 UTC, matt-lethargic commented on OpenTok/OpenTok.cs
> +        public Task DialAsync(string sessionId, string token, string sipUri, DialOptions options = null)
This is added because we should really start to be putting async methods in all of our SDKs. Would you prefer it if I added async methods for all functionality all in one PR?

2021-11-22 23:12 UTC, matt-lethargic commented on OpenTok/OpenTok.cs
> +        {
Hey Jeff, I've followed the Parameter Object pattern for this method, two reasons why I have created it like this. 

The first is that enumerating them all as parameters would mean there would be 9 different parameters, this is too many params for one method call, usually, I'd be looking to have no more than 3 or 4 max. If more options were to be added in the future it would mean even more parameters that could potentially make the code less maintainable and the SDK have an unstable interface.

The second reason is that all of the parameters in the DialOptions class are optional in the API contract, seems fitting to have them in one place that is easy to set.

I understand that we need to be consistent, but should that override good practice?

Willing to change, but would like to hear your thoughts relating to what I've just said.

2021-12-09 18:39 UTC, jeffswartz commented on OpenTok/OpenTok.cs
> +        {
That makes sense, @matt-lethargic. It's too bad we don't have named classes for options in other methods (such as the options parameter of the `OpenTok. startArchive()` method. Adding a named class here for the options is inconsistent, but it's fine I think.

2021-12-09 18:40 UTC, jeffswartz approved these changes

2021-12-16 09:09 UTC, merged