Devx 5714 - Selective Stream (Archive/Broadcast)
opentok/Opentok-.NET-SDK pull request #173
Opened 2022-02-03 17:16 UTC by matt-lethargic

Implement functionality for adding and removing streams to archives and broadcasts

2022-02-03 20:41 UTC, jeffswartz requested changes

2022-02-03 20:41 UTC, jeffswartz commented on OpenTok/OpenTok.cs
> +        /// </param>
Please add `streamMode` to the `StartBroadcast()` method. See the `streamMode` option of the REST method: https://tokbox.com/developer/rest/#start_broadcast.

2022-02-04 12:16 UTC, matt-lethargic commented on OpenTok/OpenTok.cs
> +        /// </param>
I've added this and the tests for it (also refactored the tests)

2022-02-07 10:21 UTC, closed without merging

2022-02-07 10:21 UTC, matt-lethargic commented
Closing due to bad merge