DEVX-6497 - Add Experience Composer to the OpenTok .NET Server SDK
opentok/Opentok-.NET-SDK pull request #200
Opened 2022-10-10 14:42 UTC by Tr00d

2022-12-09 07:31 UTC, HunteRoi commented
yo, i need this please merge @jeffswartz

2023-01-05 01:34 UTC, jeffswartz reviewed
Should this target the dev branch (not main)?

2023-01-05 06:46 UTC, jeffswartz requested changes
I added a commit with some docs edits and left some comments.

2023-01-05 06:46 UTC, jeffswartz commented on OpenTok/Render/ScreenResolutionConverter.cs
> +    public class ScreenResolutionConverter : JsonConverter<ScreenResolution>
Does this class need to be public?

2023-01-05 08:58 UTC, Tr00d commented
The new PR can be found [here](https://github.com/opentok/Opentok-.NET-SDK/pull/210).
I'll close this one after I addressed all comments

2023-01-05 10:16 UTC, closed without merging